#!/usr/bin/env node
/**
 * Generate dbt_heal/profiles.yml from ~/.snowflake/connections.toml
 * so PAT never needs to be re-typed into the repo.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadSnowflakeConnection } from "./snowflakeRo.js";

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);

async function main() {
  const name = process.env.CORTEX_CONNECTION || "NPSZJKJ-QP25178";
  const cfg = await loadSnowflakeConnection(name);
  if (!cfg.password) {
    throw new Error(
      `Connection ${name} has no password/PAT in ~/.snowflake/connections.toml`,
    );
  }

  const yaml = `# AUTO-GENERATED by npm run dbt:profile — do not commit
heal_demo:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ${JSON.stringify(cfg.account)}
      user: ${JSON.stringify(cfg.username)}
      password: ${JSON.stringify(cfg.password)}
      role: ${JSON.stringify(cfg.role || "ACCOUNTADMIN")}
      warehouse: ${JSON.stringify(cfg.warehouse || "COMPUTE_WH")}
      database: HEAL_DEMO
      schema: DBT_DEV
      threads: 4
      client_session_keep_alive: False
`;

  const outDir = path.join(repoRoot, "dbt_heal");
  await mkdir(outDir, { recursive: true });
  const outPath = path.join(outDir, "profiles.yml");
  await writeFile(outPath, yaml, { mode: 0o600 });
  console.log(
    `[dbt:profile] wrote ${outPath} for account=${cfg.account} user=${cfg.username}`,
  );
  console.log("[dbt:profile] file is gitignored — never commit it");
}

main().catch((err) => {
  console.error(`[dbt:profile] ${err instanceof Error ? err.message : err}`);
  process.exitCode = 1;
});
